CREATE DATABASE IF NOT EXISTS library_db;
USE library_db;

CREATE TABLE BOOK (
    MaSach   CHAR(5) PRIMARY KEY,
    TenSach  VARCHAR(200) NOT NULL,
    SoLuong  INT NOT NULL CHECK (SoLuong >= 0),
    GiaThue  DECIMAL(10,2) DEFAULT 5000
);

ALTER TABLE BOOK
ADD NgayNhap DATE;

CREATE TABLE BORROW_BOOKS (
    MaMuon   INT AUTO_INCREMENT PRIMARY KEY,
    MaSach   CHAR(5) NOT NULL,
    NgayMuon TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaSach) REFERENCES BOOK(MaSach)
);